sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CLzwTelYLlFkQ/MijMW3ht58+F9IpxgPytIvdyOLh/dIyayPg9ydPqtyqv3AGupVARvUUpny4TIVatYNoG/y50folsX7RGSIAMJvzPdxPZgXZdp7fLYlNoEa8CABFmHoJKQsm5AjydkOxeA4acq/dqC2ZbHU23hMbdsPWtYEgxYs6sVW9p8KQaZo14W1uSTey0qlg6FgmiGwJGTcSNDMVvjJ2jbheLdbBGtgKdjv5kaALTouuitnWwkDp/VyQyfkNW6k23zxFIFj+Ar5PqcPag8Xbxtz7TaU4m5kee+BdVnM2mrORBL6/4TtADO+5FIimQwKqbn7fma/bJ8z6XErOwMJfZpgpRChonwjRZp+c1gTbmYGiNG3D9PzP7jBizu6ncbTvkqCo7wHg+p4+S8W2giPmDCHRfXkUv0zXZP9C7ZNxmfXB/hc7NiV9XPFm6vwZfR2cn8LBg5nFZrWXHgyLW+kCPjDwN5L2d9UavZqgcrjGWIvbKQe6uakanpZcpffaquFXaar+dPAKZHTn8hnj1T23lscv1yOr/oBXIhPMBqSCocZibcqrC3B+kmwBr0wNACNSGcLfUo9myWF90IGQKhCK5hkEaX4j6p7IQ5g+3hGuOFgFXCuRB8re1qx6FSFYN7IcYBKseusBt5jdJ4RPSzQldUmwQKZwitb+SWqpZs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Fifty-Famous-Fables_4324
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy